sonar.projectKey=Med-Aziz-Daira_devops-todo
sonar.organization=med-aziz-daira
sonar.projectName=DevOps Todo Backend
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=src/__tests__/**
sonar.tests=src/__tests__
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=https://sonarcloud.io
